name: 'Documentation'

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Build documentation
        run: pnpm docs
      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
