name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18']
    name: Run on Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install Lerna
        run: npm i -g lerna@6.0.3
      - name: Bootstrap
        run: |
          yarn bootstrap
          yarn build
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test:coverage
      - name: Coverage
        uses: codecov/codecov-action@v1
